name: attendance
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  http: ^1.3.0
  intl: ^0.20.2
  mobile_scanner: ^6.0.5
  pretty_qr_code: ^3.3.0
  qr_flutter: ^4.1.0
  shared_preferences: ^2.5.1
  syncfusion_flutter_charts: ^28.2.4+1
  syncfusion_flutter_gauges: ^28.2.4
  url_launcher: ^6.3.1
  web_socket_channel: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
